### ISSUE TITLE
Orcherstration Validations

### ISSUE THREAD

**Issue by padnom** [hassanhabib/The-Standard#121]
Hi hassan,
I have an interogations.
In your StudentOrchestrationService

    public async ValueTask<Student> RegisterStudentAsync(Student student)
    {
        Student addedStudent =
            await this.studentProcessingService.AddStudentAsync(student);
    
        LibraryCard libraryCard = 
            await this.libraryCardPorcessingService.AddLibraryCardAsync(
                addedStudent.Id);

        return addedStudent;
    }

If AddStudentAsync call an ApIBroker and if if (student.CodeResponse== "1" or  student.CodeResponse== "10")
we dont want to add a librarycard.
We should I put the validations ?

Thx a lot, for you Job !

**Comment by hassanhabib** [comment]
@padnom  what's a code response? You mean like a failure in the API call?

**Comment by padnom** [comment]
Hi hassan,
It could be student.Age >18
Any business logic which unauthorized to add a card student.

**Comment by padnom** [comment]
@hassanhabib 
Thx for your answer.
> If you don't own that API then add the validation on your Foundation service and throw an exception maybe add the input student age and why that exception happened in the message.`InvalidStudentAgeException`

if I add this restriction into my foundationService.
And if in other orchestration service I need to add a student without this restriction  **student.Age >18.**
Should I create an other foundationService ?

If I put this business rule into my orchestrationService ?

 public class StuddentOrchestrationService
    {

        public async ValueTask<Student> RegisterStudentAsync(Student student)
        {
            ValidateStudentOnRegister(student);
            Student registeredStudent =
                await this.studentProcessingService.RegisterStudentAsync(student);

            await AssignStudentLibraryCardAsync(student);

            return registeredStudent;
        }



        public class StudentService : IStudentService
        {
            private readonly IStorageBroker storageBroker;
            private readonly IDateTimeBroker dateTimeBroker;
            private readonly ILoggingBroker loggingBroker;

            public StudentService(
                IStorageBroker storageBroker,
                IDateTimeBroker dateTimeBroker,
                ILoggingBroker loggingBroker)
            {
                this.storageBroker = storageBroker;
                this.dateTimeBroker = dateTimeBroker;
                this.loggingBroker = loggingBroker;
            }

            public ValueTask<Student> RegisterStudentAsync(Student student) =>
            TryCatch(async () =>
            {
                ValidateStudentOnRegister(student);
                return await this.storageBroker.InsertStudentAsync(student);
            });




            private void ValidateStudentOnRegister(Student student)
            {
                if (student.Age > 18)
                {
                    throw new InvalidStudentRegistrationException(
                            parameterName: nameof(StudentRegistration.Age),
                            parameterValue: student.Age);
                }
            }
        }

**Comment by hassanhabib** [comment]
@padnom if this restriction is only specific to a particular orchestration flow then you should put that validation rule at the orchestration service layer.

I have to warn you though, if you have different rules for persisting the same type of data/entities into your system - your data then becomes inconsistent. Because some records in the system will follow the >18 rule and some other records won't. I don't think that's a good design.

You should find a way to differentiate profiles who follow the > 18 rule versus profile that don't with maybe an additional property like `Type` that says maybe `Adult` or completely create two different entities like `AdultProfiles` and `MinorsProfiles`. I hope this helps.

**Comment by padnom** [comment]
@hassanhabib 
Thx for you answer.
As you said I will create different entites.
