### ISSUE TITLE
Log 

### ISSUE THREAD

**Issue by padnom** [hassanhabib/The-Standard#127]
Hi @hassanhabib ,

An another interogations. Maybe you mentionned that but didn't found it.

```
public async ValueTask<Student> AddStudentAsync(Student student) =>
TryCatch(async () => 
{
    ...
    Student addedStudent = await this.studentService.AddStudentAsync(student);
    LibraryCard libraryCard = await this.libraryCard.AddLibraryCard(addedStudent.Id);

    return addedStudent;  
});
```

In case of errors into StudentService.
Won't we log twice the same informations ? One time into StudentService then into StudentOrchestrationService.

Thx

**Comment by hassanhabib** [comment]
@padnom good question.

Every service will log a trace of the issues it's dealing with individually and in isolation.
In The Standard I talked for a bit about this concept: [Every Service for Itself](https://github.com/hassanhabib/The-Standard/blob/master/2.%20Services/2.%20Services.md#2024-every-service-for-itself) - where I explained that every service operates fully independently from it's dependencies and it's consumers.

In the logging scenario the timeline would look as follows:
### FOUNDATION SERVICE
CATEGORY: Student Validation Exception
ISSUE: Invalid Student Exception
DETAILS:
- Student Name is required

### PROCESSING SERVICE
CATEGORY: Student Processing Dependency Validation Exception
ISSUE: Invalid Student Exception
DETAILS: 
- Student Name is required

### ORCHESTRATION SERVICE
CATEGORY: Student Orchestration Dependency Validation Exception
ISSUE: Invalid Student Exception
DETAILS: 
- Student Name is required

This time line is telling us where the error went and how it was handled at every service. While this might _seem_ redundant, it actually helps engineers aggregate issues and errors in a given request. For instance, let's say your orchestration service is also doing non-circuit breaking validations where it decides to continue until processing and foundation services downstream also have a say in terms of validations. Your logging at the orchestration service would look like this:

### ORCHESTRATION SERVICE
CATEGORY: Student Orchestration Dependency Validation Exception
ISSUE: Invalid Student Exception
DETAILS: 
- Student Name is required
- Student Library Card doesn't exist

Now, your orchestration service is _collecting_ issues from all downstream services and making an independent decision on whether to continue or cut the circuit. This pattern helps a lot with defining business critical paths.

There's also the other aspect where your Orchestration service decides to rollback previous details. In this case we want to log and trace where the exception has stopped propagating and where a decision has been made to either retry or rollback the process accordingly.

I hope this helps.

**Comment by padnom** [comment]
Hi @hassanhabib
Thx a lot for your response.
It help me a lot to understand your point of view.
I didn't think to the retry or anything else
I start to integrate standard in somes microservices.
And I have to admin it bring me to a next level.

Thx keep going to do your videos
