### ISSUE TITLE
brokers

### ISSUE THREAD

**Issue by padnom** [hassanhabib/The-Standard#153]
Hi Hassan, 
I'm still in learning curve with "The-Standard".

If I need to generate a studentcard number with some algorithmics without call to any "Entity Brokers" etc...

Usually I would have made a static method like this.
`public static string StudentServiceHelpers.GenerateCardReference()
{
_some logic...._
}`
But in your recommandation, you said to avoid helpers etc....
Should I create StudentCardBroker like DateTimeBroker to be in respect with "The-Standard" convention.

StudentCardBroker  should be a "support brokers" or a "Entity Brokers" ?

Or maybe I'm completely wrong....

By the way ,
I'm start to present in my compagny "The standard".

Thx a lot !

**Comment by hassanhabib** [comment]
@padnom `GenerateCardReference` should be a service. because you said it has logic. logic is testable. testable components are Services.
