### ISSUE TITLE
Orchestration Service Model

### ISSUE THREAD

**Issue by eriadhami** [hassanhabib/The-Standard#25]
@hassanhabib bro, i am trying to implement orchestration service in a project and i have a question. The orchestration layer may live after the exposers and exposesers may introduce new models which will be mapped, so in your opinion do we need to create these new models in Models folder?

**Comment by hassanhabib** [comment]
@eriadhami correct. Your Orchestration services may have their own models. If you break your models folder into Foundations, Processings and Orchestrations then you can easily place these models under the Orchestrations folder.

Now, exposers (Controllers, gRPC or UI Components) should not have their own models, only services can have that kind of power. I hope this helps.

**Comment by eriadhami** [comment]
@hassanhabib I appreciate the time you've committed to providing me with mentoring

**Comment by eriadhami** [comment]
> @eriadhami correct. Your Orchestration services may have their own models. If you break your models folder into Foundations, Processings and Orchestrations then you can easily place these models under the Orchestrations folder.

@hassanhabib so we must validate these models and have new exceptions also

**Comment by hassanhabib** [comment]
On the orchestration level, you only validate what your service is using.

Here's an example, if your orchestration service is receiving a `Student` model and just passing it downstream to another service. then the only validation you need to perform is to ensure student is not null.

If you use both student id and student then you need to validate what you use. the same concept applies to any service type that is not Foundation (Processing, Orchestration ... etc) Read more about that here:
https://github.com/hassanhabib/The-Standard/blob/master/2.%20Services/2.2%20Processings/2.2%20Processings.md#2223-used-data-only-validations
