### ISSUE TITLE
CODE RUB: Change UpsertData() method to UpsertDataList()

### ISSUE THREAD

**Issue by YaqubAliy02** [hassanhabib/The-Standard#278]
private void Validate(params (dynamic Rule, string Parameter)[] validations)
{
    var invalidStudentException = new InvalidStudentException(
        message: "Student is invalid. Please fix the errors and try again.");

    foreach((dynamic rule, string parameter) in validations)
    {
        if(rule.Condition)
        {
            invalidStudentException.UpsertData(parameter, rule.Message);
        }
    }

    invalidStudentException.ThrowIfContainsErrors();
}

**Comment by glhays** [comment]
@YaqubAliy02 Good eye catching this. Are you going to resolve this with a pull request.
