### ISSUE TITLE
CODE RUB: Change `equivelant` -> `equivalent` 

### ISSUE THREAD

**Issue by ZafarUrakov** [hassanhabib/The-Standard#281]
https://github.com/hassanhabib/The-Standard/blob/dad8c12c56b1e231c3c52beb236a29f2cb8ad0b5/2.%20Services/2.1%20Foundations/2.1%20Foundations.md?plain=1#L80

**Comment by glhays** [comment]
HI @ZafarUrakov Good catch. Do you have intentions to resolve this issue?

**Comment by ZafarUrakov** [comment]
> HI @ZafarUrakov Good catch. Do you have intentions to resolve this issue?

Hi, yep. Let me do it.
