### ISSUE TITLE
Some questions about standard.

### ISSUE THREAD

**Issue by padnom** [hassanhabib/The-Standard#88]
Hi,
Your work is amazing thank you so much.
I try to read all your content. I have some questions

**Brokers 1.2.5 Naming Conventions** 
If  I have a MongoStorageBroker for a student service  and SqlStorageBroker for teacherService
So If I understood correctly, I  need to implement IMongoStorageBroker  ISqlStorageBroker ?

**CleanArchitecture**
I try  to understand.
If I want to implement clean architecture like ardalis https://github.com/ardalis/CleanArchitecture with broker.
In which layer Broker  should be put ? The infrastructure layer ?

![image](https://user-images.githubusercontent.com/20400123/152137821-7f040a34-d711-499f-ba4f-be70d51a5e7d.png)

Thanks !

**Comment by hassanhabib** [comment]
@padnom So, brokers in general live in the same realm as your services and exposure components (say controllers for your APIs for instance).

In your scenario, I would have an `ISqlStorageBroker` and `IMongoStorageBroker` for each implementation.
The reason for that, is that your interface/contract won't be able to withstand both. So go that route.

**Comment by padnom** [comment]
@hassanhabib 
Thx for you reply.
I'm little bit confuse because in Infrastructure layer.
This layer contains classes for accessing external resources such as file systems, web services, smtp, and so on. These classes should be based on interfaces defined within the application layer.
 usualy I saw Repositories implementation.
![image](https://user-images.githubusercontent.com/20400123/152311270-ae369fc5-10f8-4c7d-a1df-caf13355672a.png)

**Comment by hassanhabib** [comment]
@padnom the concept of infrastructure to give you access to external resources might not support your ability to access resources within the system you're running on.
For instance, let's say we want `DateTimeBroker` where are you going to put that? Is it in the infrastructure? but it's not exactly external?

The other thing here is that the approach you mentioned seems to rely heavily on foundation services (core logic) owning the contract and brokers having to adhere to it. At first glance, this seems very convincing. But then you truly try to switch brokers and now you end up writing business logic (selection, iteration or sequencing) into your thin layer of integration.

If we are trying to achieve true abstraction here. then we need to first understand that doing it in one step isn't realistic without breaking some rules. in The Standard abstract happens on two different steps. 
First step is to abstract away native/external functionality. and the second step is to abstract away contracts.

There's also another aspect here in terms of sharing libraries to provide access to resources. I'm not sure this is the best route to go about that. creating centralized components that are used across multiple microservices always causes a single-point-of-failure situation.

Let's jump on a call and discuss this on Discord.

**Comment by padnom** [comment]
Thanks, I understand better.
I understand what you said.
I would have liked to do this on discord.
Unfortunately, my English is so bad :D.

**Comment by hassanhabib** [comment]
@padnom my English isn't any better either lol
Closing this issue.
